spring.application.name=gateway-apllication
spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=member-service
spring.cloud.gateway.routes[0].uri=lb://member-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/members/**
