spring.application.name=gateway-application
spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=member-service
spring.cloud.gateway.routes[0].uri=lb://member-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/members/**

spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**,/auth/**

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
