spring.application.name=gateway-apllication
spring.main.web-application-type=reactive

spring.cloud.gateway.routes[0].id=status-route
spring.cloud.gateway.routes[0].uri=forward:/status-endpoint
spring.cloud.gateway.routes[0].predicates[0]=Path=/status

spring.cloud.gateway.routes[1].id=mock-members
spring.cloud.gateway.routes[1].uri=https://httpbin.org
spring.cloud.gateway.routes[1].predicates[0]=Path=/mock/members
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/mock/members, /get
